### ISSUE TITLE
all_phrases specification inconsistent

### ISSUE THREAD

**Issue by chadpalmer2** [learn-co-curriculum/programming-univbasics-3-methods-scope-lab#2]
it is stated that "This method does not need to take any parameters, but should call the mario, toadstool, and link phrases." however, the test says "takes in an argument and puts out the catch phrase", suggesting that the method should take an argument.

**Comment by maxwellbenton** [comment]
Hi @chadpalmer2,

Thank you for spotting this and providing feedback! We've updated the test message for this lab so that it correctly aligns with the Readme and test expectation, which should resolve this issue going forward.

Thank you for contributing to a Learn lesson!
